wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.10.9
    start_time: 1680610134.975375
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.10.9
      5: 0.13.11
      8:
      - 2
      - 5
